-- +goose Up
CREATE TABLE users (
id UUID PRIMARY KEY UNIQUE,
email VARCHAR(255) NOT NULL UNIQUE,
created_at TIMESTAMP NOT NULL DEFAULT NOW(),
updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE tasks(
id UUID PRIMARY KEY UNIQUE,
user_id UUID NOT NULL ,
title VARCHAR(255) NOT NULL,
description TEXT ,
priority INTEGER NOT NULL DEFAULT 1,
completed BOOLEAN NOT NULL DEFAULT FALSE,
due_date DATE,
created_at TIMESTAMP NOT NULL DEFAULT NOW(),
updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- +goose Down

DROP TABLE tasks;
DROP TABLE users;
