// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func TaskForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form hx-post=\"/api/tasks\" hx-swap=\"outerHTML\" hx-target=\"this\" hx-on::afterRequest=\"this.reset()\" class=\"bg-jet-black w-lg mx-auto p-4 space-y-4 border border-argentinian-blue rounded-xl\"><label class=\"block\"><input name=\"title\" class=\"p-2 w-full rounded bg-eggshell-white\" type=\"text\" placeholder=\"Task Title\"></label> <label class=\"block\"><textarea name=\"description\" class=\"p-2 w-full rounded bg-eggshell-white\" placeholder=\"Description\"></textarea></label><div class=\"flex justify-between\"><label class=\"block\"><span class=\"text-eggshell-white text-sm\">Due Date</span> <input name=\"due-date\" class=\"p-2 rounded bg-eggshell-white\" type=\"date\" placeholder=\"Task Title\"></label></div><button type=\"submit\" class=\"bg-argentinian-blue w-30 p-2 rounded-2xl hover:scale-105 hover:cursor-pointer active:scale-95\">Add</button></form><div id=\"confirmation-container\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
